# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 311d985e8c11b6941ed8d5be8f1027ff76e569eab9b38b85654d4028c39f26bc8f47888e7ec7c87961ebb6081d6091eb2e69723eb547625d04af1c5b7a1eda1e

test:
  secret_key_base: 568fe9b856c2dc003ec525d7841d9cc2f66771e105ba9e3eee3ee86139e175de44093213509742de37066ed9ffe8651ee00f53590b81ae57a58d440dcf1d1669

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
